name: xibo-player
base: core20
version: 1.8-R7
summary: Xibo Linux Player
description: Xibo for Linux Digital Signage Player
grade: stable
confinement: strict

architectures:
  - build-on: amd64

slots:
  dbus-daemon: # name this whatever you want
    interface: dbus
    bus: session
    name: org.gtkmm.xibo # adjust accordingly

apps:
  xibo-player:
    command: usr/bin/snap_run.sh xibo-watchdog
    plugs: [gsettings, network, home, audio-playback, screen-inhibit-control, framebuffer, opengl]
    slots: [dbus-daemon]
    extensions: [gnome-3-38]

  disabled-watchdog:
    command: usr/bin/snap_run.sh xibo-watchdog --disable-restart
    plugs: [gsettings, network, home, audio-playback, screen-inhibit-control, framebuffer, opengl]
    slots: [dbus-daemon]
    extensions: [gnome-3-38]

  options:
    command: usr/bin/xibo-options
    plugs: [gsettings, network, home]
    slots: [dbus-daemon]
    extensions: [gnome-3-38]

parts:
  base:
    plugin: nil
    build-packages:
      - software-properties-common
      - apt-transport-https
      - ca-certificates 
      - gnupg 
      - curl 
      - wget
      - unzip
      - libxss-dev
      - libssl-dev
      - cmake
      - g++

  # FIXME: use from APT
  boost:
    plugin: nil
    override-pull: |
      add-apt-repository ppa:mhier/libboost-latest
      apt-get update
      apt-get install -y libboost1.70-dev
    after: [base]

  # FIXME: don't build in pull step
  cryptopp:
    plugin: nil
    override-pull: |
      curl -o cryptopp.tar.gz -SL https://github.com/weidai11/cryptopp/archive/CRYPTOPP_8_1_0.tar.gz && \
      curl -o cryptopp_pem.zip -SL https://github.com/noloader/cryptopp-pem/archive/095f08ff2ef9bca7b81036a59f2395e4f08ce2e8.zip && \
      tar -zxvf cryptopp.tar.gz && \
      unzip -a cryptopp_pem.zip && \
      cp -r cryptopp-pem-095f08ff2ef9bca7b81036a59f2395e4f08ce2e8/. cryptopp-CRYPTOPP_8_1_0 && \
      cd cryptopp-CRYPTOPP_8_1_0 && \
      make -j4 && \
      make install

  date-tz:
    source: https://github.com/HowardHinnant/date/archive/v3.0.0.tar.gz
    plugin: cmake
    build-packages:
      - libcurl4-gnutls-dev
    cmake-parameters:
      - -DBUILD_TZ_LIB=ON
      - -DBUILD_SHARED_LIBS=ON
      - -DUSE_SYSTEM_TZ_DB=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
    after: [base]

  sqlite-orm:
    source: https://github.com/fnc12/sqlite_orm/archive/refs/tags/1.6.tar.gz
    plugin: cmake
    build-packages:
      - libsqlite3-dev
    cmake-parameters:
      - -DBUILD_TESTING=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr
    after: [base]

  # FIXME: this should be replaced with libwebkit2gtk
  webkitgtk3:
    plugin: nil
    override-pull: |
      echo "deb http://ru.archive.ubuntu.com/ubuntu/ bionic main universe" >> /etc/apt/sources.list
      apt-get update
      apt-get install -y libwebkitgtk-3.0-dev
    after: [base]

  player:
    source: player
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DAPP_ENV=SNAP
      - -DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage-packages:
      - libglu1-mesa
      - freeglut3
      - libzmq5
      - libboost1.70
      - libgtkmm-3.0-1v5
      - libcanberra-gtk3-module
      - libwebkitgtk-3.0-0
      - libgpm2 # gstreamer warning
      - libslang2 # gstreamer warning
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-base
      - gstreamer1.0-gl
      - gstreamer1.0-libav
      - gstreamer1.0-gtk3
      - libspdlog1
    build-packages:
      - libgtkmm-3.0-dev 
      - libglibmm-2.4-dev
      - libzmq3-dev
      - libspdlog-dev
      - libgtest-dev
      - libgmock-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
    after: [webkitgtk3, boost, date-tz, sqlite-orm] 
